# reference and MiSeq samples
import os
import sys
import csv
from Bio import SeqIO

SAMPLES_LIST = '/home/ozagordi/Projects/MinVar/data/MinVarSamples.csv'
MINVAR_EXE = '/home/ozagordi/Dropbox/Software/MinVar/bin/minvar'
MIXES = [9, 10, 11, 12, 17, 18, 19, 20]

run_dict = {}
with open(SAMPLES_LIST, 'r') as csvfile:
    run_list = csv.DictReader(csvfile)
    for r in run_list:
        if r['Sample_ID'] in run_dict.keys():
            run_dict[r['Sample_ID']][r['key']] = r['value']
        else:
            run_dict[r['Sample_ID']] = {}

def get_fastq(wildcards):

    import glob
    from Bio import SeqIO
    mix = 'Mix_{}'.format(wildcards.id)
    dir_454 = run_dict[mix]['X454_data_folder']
    mid_str = run_dict[mix]['X454_MID']

    full_amp_dir = [d for d in os.listdir(dir_454) if d.endswith('fullProcessingAmplicons')]
    assert len(full_amp_dir) == 1, full_amp_dir
    sff_dir = os.path.join(dir_454, full_amp_dir[0], 'sff')
    indiv_sff = glob.glob('%s/*.sff' % sff_dir)
    assert len(indiv_sff) == 1, sff_dir
    sff_file = indiv_sff[0]
    return sff_file

rule all:
    input:
        #'fastq_dir/9.sff'
        expand("images/scatter_plot_mix_{id}.pdf", id=MIXES),
        expand("summary/precrec_{id}.csv", id=MIXES)

rule mix2sff:
    input:
        get_fastq
    output:
        'fastq_dir/{id}.sff'
    run:
        mix = 'Mix_{}'.format(wildcards.id)
        mid_str = run_dict[mix]['X454_MID']
        shell("sfffile -o fastq_dir/{wildcards.id}.sff mid{mid_str}@{input}")

rule sff2fastq:
    input:
        'fastq_dir/{id}.sff'
    output:
        'fastq_dir/{id}.fastq'
    run:
        conv = SeqIO.convert(input[0], 'sff-trim', output[0], 'fastq')
        print('Converted %d reads' % conv)

rule minvar_run:
    input:
        'fastq_dir/{id}.fastq'
    output:
        'minvar_results_{id}/annotated_DRM.csv',
        odir='minvar_results_{id}',
        logfile="minvar_results_{id}/minvar_{id}.err"
    shell:
        "cd {output.odir}; \
        {MINVAR_EXE} -f ../{input} &>> ../{output.logfile}"

rule plots:
    input:
        "minvar_results_{id}/annotated_DRM.csv"
    output:
        "images/scatter_plot_mix_{id}.pdf"
    run:
        shell("Rscript scatterplots.R {wildcards.id}")

rule precrec:
    input:
        "minvar_results_{id}/annotated_DRM.csv"
    output:
        "summary/precrec_{id}.csv"
    run:
        shell("Rscript precrec.R {wildcards.id}")

# onsuccess:
#     try:
#         os.remove('Rplots.pdf')
#     except FileNotFoundError:
#         pass
#     for i in MIXES:
#         os.remove('fastq_dir/%d.fastq' % i)
